apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-consumer
  namespace: services
  labels:
    app: message-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-consumer
  template:
    metadata:
      labels:
        app: message-consumer
    spec:
      containers:
      - name: message-consumer
        image: doodlehaus/message-consumer:latest
        imagePullPolicy: Always
        env:
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_URL
          value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASS)@rabbitmq.infrastructure.svc.cluster.local:5672"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
